<div class=" x_panel">
    <ol class="breadcrumb">
         <li>
            <a href="<?php echo $this->url('administracao') ?>">
                <?php echo $this->translate('Início') ?>
            </a>
         </li>
         <li>
             <a href="<?php echo $this->url('usuario') ?>">
                <?php echo $this->translate('Usuário') ?>
             </a>
         </li>
         <li class="active">
             <?php echo $this->translate('Editar Usuário') ?>
         </li>
    </ol>
</div>

<div class="x_panel">
    <div class="x_title">
        <h2>Editar Usuário</h2>
        <div class="clearfix"></div>
    </div>


<?php
    $form = $this->form;
    $form->setAttribute('class', 'form-horizontal form-label-left');
    if ($this->success){
      echo  '<div class="alert alert-success">' . $this->success[0] . '
                <button type="button" class="close" data-dismiss="alert">x</button>
            </div>'; 
    }
    if ($this->error){
       echo '<div class="alert alert-danger">' . $this->error[0] . '
            <button type="button" class="close" data-dismiss="alert">x</button>
       </div>'; 
    }
    
    
    $this->formElementErrors()
         ->setMessageOpenFormat('<div class="alert alert-warning">
                                    <button type="button" class="close" data-dismiss="alert">x</button>')
         ->setMessageCloseString('</div>')
         ->render($form);
    
    $form->setAttribute('action', $this->url('usuario/default' , array('controller' => "Usuario" , 'action' => 'editar' , 'id' => $this->id)));
    
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    <div class="form-group">
        <label for="nome" class="control-label col-md-3 col-sm-3 col-xs-12">
            Nome
            <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('nome')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            E-mail
            <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('email')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Login
            <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('login')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Status
            <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('status')); ?>
        </div>
    </div>
    
    <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <?php echo $this->formRow($form->get('submit')); ?>
        </div>
    <div>
    
</div>
  